### ISSUE TITLE
union allows distinct constants to be in the same eclass

### ISSUE THREAD

**Issue by ztatlock** [mwillsey/egg#1]
This maybe more of an RFC than an issue, but right now, union will not complain if two eclasses A and B are merged where both A and B contain distinct constants.

Some hypothetical clients may want support for such situations, but an eclass containing distinct constants will usually be a bug in a rewrite rule or other equivalence finder running over the egraph.

A straightforward fix would be to extend the range type of the eclass's hash map (currently `Vec<ENode>`) in the egraph type to also track what constant (if any) an eclass contains.  Then union can quickly check for compatibility during merging.

More interestingly, this would be a first step towards supporting client-specific equivalence finders, constant folding in particular.  I'm not sure what that interface looks like yet, but getting it right will be an important design challenge.

**Comment by remysucre** [comment]
This makes sense for constant folding; what other equivalence finders are you thinking of?

**Comment by ztatlock** [comment]
The most natural use is actually for non-equivalence -- for Rete-style pattern matching you can know for certain that two eclasses will never merge if they contain distinct constants.

The constants might also be useful for finding denser representations of larger values like lists, e.g., if an eclass contains `[1, 2, 3, ..., 100]` we may want to merge that with an eclass for `map ((+) 1) (range 100)`.

**Comment by remysucre** [comment]
I'm starting to like this idea. So far classes seem oblivious to the semantics of the domain, and assigning constant values to each class can be the beginning of adding more meaning & structure to them.

**Comment by remysucre** [comment]
We discussed offline to add more expressive annotations, see the doc for details: https://docs.google.com/document/d/1IZ3RI97x6VNkHkyO13Iq5gu6T2VAsiZ0YboTr3VaMBM/edit?usp=sharing

**Comment by mwillsey** [comment]
This will be subsumed by #8, closing.
