### ISSUE TITLE
Docs feedback

### ISSUE THREAD

**Issue by tlringer** [mwillsey/egg#16]
I'm just dropping in my requested feedback in a place that's easy to find. I haven't moved on yet to using Egg, so this is just based on reading the docs:

1. The installation was very smooth. I was impressed.
2. It was also a very nice experience opening up the docs the first time.
3. The page on egraphs is fantastic and understandable.
4. There's a very small typo ("conceptually and") on the graphs page.
5. The examples on both the main page and the egraph page are hard for me to understand without context. It would help to have an English explanation before each of them about what is happening.
6. Better yet, I would love some kind of tutorial to getting starting with Egg that walks you through a real but simple use case. Maybe even in the browser!
7. The main page could also use a "What is Egg?" section at the beginning, or just a paragraph at the top. Some of the wonderful content from the egraph page could go in that section.

I'll add other thoughts to this issue as I move on to playing around.

**Comment by tlringer** [comment]
Reading APIs: I found this very overwhelming. I think this is not because the APIs are confusing, but just because I need this all more tutorialized. In particular, with so much going on, it's hard for me to imagine where to start. I'm considering playing around with a toy example based equivalences I see in DEVOID, and I have no idea how I'd express my language to Egg to get started with that. I think I'd like a tutorial that walks through, say, a simple arithmetic language that does some AC rewriting. It looks like maybe that's what's happening on the first page, but without an explanation I just feel lost.

**Comment by tlringer** [comment]
Running the tests the first time worked with no issues.

**Comment by tlringer** [comment]
`math.rs` is cool. If you are doing a simple example for a tutorial, I think you could take `math.rs` and trim it down so there are fewer features. Show from the start what each step means and why you would do it. Then perhaps later you could add new rules and explain what they do.

Why are some rules in `math.rs` commented out?

What is happening in the metadata? The first thing that it would be fun for me to play with would be proof production, for some really silly notion of "proof." (Maybe that's a hard use-case that would require some hacking; I'm not sure.) I could just set that proof to be "reflexivity" by default, and then I'm guessing I can specify how to change the proof every time two Eclasses merge? My Eclasses may need to each maintain several proofs; I'm not sure. In any case, it would be cool if any tutorial included storing metadata with nontrivial merging behavior.

**Comment by tlringer** [comment]
This is as far as I got in the allotted hour. Looking forward to Tuesday!

**Comment by mwillsey** [comment]
Much of this has been addressed in the latest release, including the tutorial!
