### ISSUE TITLE
Depth in union_depth aways 0

### ISSUE THREAD

**Issue by remysucre** [mwillsey/egg#18]
It seems the `depth` argument in [`union_depth`](https://github.com/mwillsey/egg/blob/dd172ef77279e28448d0bf8147e0171a8175228d/src/egraph.rs#L537) is never used but for debugging, and it is always 0. Should it be removed?

**Comment by mwillsey** [comment]
Yeah, it's an artifact of an old parent-pointers implementation. It should be removed. It's been moved to `upward` now. Although there is still something a little busted about parent-pointers, I'm still trying to figure out what exactly it is.
