### ISSUE TITLE
constant folding

### ISSUE THREAD

**Issue by mwillsey** [mwillsey/egg#2]
We should implement constant folding. The `Language` trait should provide the functionality to do that.

**Comment by remysucre** [comment]
Is pruning code working? I'm thinking to follow the `prune` function for folding. That is, match on nodes that are `op const const ...`, evaluate them, then add in the result as a node.

**Comment by remysucre** [comment]
FYI I'm working on adding an `eval` method to the `Language` trait and then implement folding as above.

**Comment by remysucre** [comment]
Hmm this isn't as simple as I thought, since the matcher seems necessary here. The suggestion by @ztatlock in #1 could help, but it's a bit weird to have `union` handle constants.

**Comment by ztatlock** [comment]
Doing it in `union` is really just to incrementalize; it could be a separate pass too.  That said, there are a lot of bottom-up passes that can generically be incrementalized through `union` so worth considering?
