### ISSUE TITLE
Runner doesn't track initial rebuild

### ISSUE THREAD

**Issue by oflatt** [mwillsey/egg#23]
There is an initial rebuild at the beginning of `run` in `run.rs` that is there to create the initial `classes_by_op` hash table in the egraph. The time for this rebuild (usually very small) is not tracked by the iterations vector in the runner.

**Comment by mwillsey** [comment]
I feel like that's ok, as it's not really part of the "running". I'm not sure it's worth introducing a new place to track these kinds of start-up costs.
