### ISSUE TITLE
Bidirectional rewrite! macro

### ISSUE THREAD

**Issue by remysucre** [mwillsey/egg#31]
It's common to have rewrite rules to apply both ways, so it'd be convenient to have a bidirectional rewrite! macro. Such a macro (say `equiv!`) can generate a vector of 2 rules, and the user can use it like so: 

```
vec![
    equiv!("assoc"; "(* a (* b c))" = "(* (* a b) c)"), 
    equiv!(...), 
    ...
].concat()
```

This will also force the user to separate bidirectional rules from one-way rules, which is good.

**Comment by remysucre** [comment]
p.s. it should panic if both sides don't have the same variables.

**Comment by mwillsey** [comment]
I opened #32 for the second part.

Why do you think they should be separated? I kinda think it'd be cool to be able to write them inline with the one-way rules. Although that poses an API challenge that separating them (as you've said) already solves.

**Comment by mwillsey** [comment]
nvm im convinced
