### ISSUE TITLE
unresolved import `egg::Symbol` 

### ISSUE THREAD

**Issue by avanhatt** [mwillsey/egg#34]
The documentation suggests importing egg's interned String as `egg::Symbol`, but this fails to build in a clean new project (created with `cargo new`, `egg v0.4.1`):

```egg-test $ cargo run
   Compiling autocfg v1.0.0
   Compiling log v0.4.8
   Compiling cfg-if v0.1.10
   Compiling symbolic_expressions v5.0.3
   Compiling smallvec v1.4.0
   Compiling once_cell v1.4.0
   Compiling instant v0.1.4
   Compiling indexmap v1.4.0
   Compiling egg v0.4.1
   Compiling egg-test v0.1.0 (/Users/avh/research/egg-test)
error[E0432]: unresolved import `egg::Symbol`
 --> src/main.rs:1:5
  |
1 | use egg::Symbol;
  |     ^^^^^^^^^^^ no `Symbol` in the root
```

**Comment by mwillsey** [comment]
Do the [published docs](https://docs.rs/egg/0.4.1/egg/) suggest doing that? I haven't cut a release with the symbol thing on yet.

To fix, either don't use `Symbol`, or you can use a [git dependency](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories) to use the latest-and-greatest egg (make sure to pin to a `rev` so you don't get surprise changes).

**Comment by avanhatt** [comment]
Whoops, no, I was looking at my local docs - sorry and thanks for the quick answer!
