### ISSUE TITLE
BiImplication in prop example

### ISSUE THREAD

**Issue by ratmice** [mwillsey/egg#42]
Mostly curious, from my own projects/converting between normal forms, In the the [prop.rs](https://github.com/mwillsey/egg/blob/974dd7699152a0e49fafbc013263bcceb116189e/tests/prop.rs#L32) example, Introducing BiImplication tends to increase the complexity of the ast, because assuming you add an enum variant like: `"<->" = BiImplication([Id; 2]),`
and a case to _make_ `Prop::BiImplication([a, b]) => Some(x(a)? || !x(b)?) &&  Some(x(b)? || !x(a)?),`,
you would need to either `clone`, or `Rc`, `a` and `b`.

So introducing BiImplication causes the ownership to get a bit hairier.
I thought it'd be interesting to see how that small change affects the otherwise clean example,
however I haven't tried it in egg yet.

**Comment by mwillsey** [comment]
`a` and `b` are just [`Id`](https://docs.rs/egg/0.6.0/egg/struct.Id.html)s, which implement `Copy`, so there shouldn't be any ownership problems.

Feel free to fork and try it out! I think just adding the line should work:
```
Prop::BiImplication([a, b]) => Some(x(a)? == x(b)?),
```

**Comment by ratmice** [comment]
I see, by not normalizing from `Prop -> Prop` the ownership is vastly simplified, Will definitely give it a try.

**Comment by mwillsey** [comment]
Great! Feel free to open another issue if you have more questions.
