### ISSUE TITLE
Put fuel on "expansive" rules

### ISSUE THREAD

**Issue by mwillsey** [mwillsey/egg#6]
There should be some way to classify rewrites as expansive or not, and those that are should have some kind of fuel applied to them.

Can we do this classification automatically?

**Comment by remysucre** [comment]
Can you give an example of such a rule? Sometimes one can structure the rules so that expansive rules in effect only fire on demand.

**Comment by mwillsey** [comment]
Firing on-demand is tricky. What constitutes demand?

Examples of rules that will eventually saturate, but will blow things up first are the combinations of commutativity, associativity, and distributivity.

**Comment by mwillsey** [comment]
Closed by f7b7b61.
