### ISSUE TITLE
Track applied rules for each class

### ISSUE THREAD

**Issue by remysucre** [mwillsey/egg#9]
Herbie has an optimization that tracks the rules applied for each class, so that we can skip those rules if the class doesn't change. This could speed up searching quite a bit when each class is big. This could be a simple annotation once we have class metadata.

**Comment by remysucre** [comment]
Any thoughts on this, now that we have metadata? I'd really like to have this, because I have a rule that keeps firing on the same term (similar to alpha renaming).

**Comment by remysucre** [comment]
Actually that wouldn't work. The metadata is on classes, but rules are applied to nodes.

**Comment by mwillsey** [comment]
Closing in favor of (hopefully soon) forthcoming search optimizations.
